### ISSUE TITLE
My images disappeared

### ISSUE THREAD

**Issue by dh256git** [Grapheel/IRIS#1]
## Tell us about your system and the issue with IRIS

For [option1/option2/option3...] delete as appropriate.

1. I'm using IRIS as a visually impaired user
2. My device is a: Macbook Pro 13" 2015 (high spec)
3. My operating system is: OS X 10.10
4. The web browser I'm using is: Safari
5. I'd like to report or request a: bug with existing feature
6. I found the following bugs:
 - [ ] the images I uploaded yesterday were not there when I logged in today,
 7. I'd like to request the following IRIS superpower(s), change(s):
 - [ ] sort images in order of number of replies from top to bottom,
 - [ ] notification sound when I upload an image,

## My further comments:

Add or remove as appropriate.

I have the following comments:
- [ ] Great project but faster responses would be good,
- [ ] Tim is awesome.

**Comment by tingard** [comment]
Hi there, thanks for pointing this out. Could you confirm for me whether these images are again visible?

**Comment by tingard** [comment]
For future reference, please keep bug reports separate from feature requests to allow us to easily track what each issue is about (in this case two issues would have been better, one for the missing images and another for the requested features)
