### ISSUE TITLE
Profile preferences don't seem to be working

### ISSUE THREAD

**Issue by PhysicsLagomorph** [Grapheel/IRIS#11]
### About me and my system

1. I'm using IRIS as a [volunteer]
2. I am using assistive technology: [No]
3. My device is a: A) Samsung mobile B) Surface tablet
4. My operating system is: A) Android B) Windows 10
5. The web browser I'm using is: A) Android mobile B) Firefox
6. The version of the web browser is: 

### Bugs found with description

I found the following bug(s):

- I have saved my profile preferences for example, show me only physics and maths in my profile settings. However, in the main display with the house icon it shows me all pictures including biology and computer science images. This is not a problem as such as filtering on the house page seems to correctly select the images. However, then I do not see the point of the profile preferences/conclude they must not be working. It would of course be most convenient to have images automatically filtered for your preferences. I tested this on both my phone and laptop.

**Comment by tingard** [comment]
Hi @PhysicsLagomorph, thanks for testing IRIS! I agree the way the profile filtering is setup is confusing.

The future plan is to show only a couple of images at a time, rather than every image on IRIS, hence the settings. 

However, while we have a small number of images it's easier for the developer team if all images are shown.

Can I ask whether you think you would prefer to see all available images in your selected range, or have us try and create a custom shortlist for you?

**Comment by PhysicsLagomorph** [comment]
I think I would prefer to see all images, as I am fussy and like to pick and choose, but with it pre-filtered of what I am capable of answering ie subject as set in the preferences. To limit page loading times if there are a load of images you would probably need to break it into multiple pages or truncate it somewhere. I would rank images by time submitted alone, ie oldest first so the oldest items are at the top of the page to keep users waiting as little time as possible. But that is just my instinct, you may have better plans!

**Comment by tingard** [comment]
Thanks for your suggestions!
Prioritising images that have been waiting for a response for a long time is definitely a priority. The current plan is to show batches of 6-8 images at the user's level, with a "refresh images" button to request more. This system is something we'll probably end up A/B testing though!
