### ISSUE TITLE
Help computer scientist student - Bug

### ISSUE THREAD

**Issue by Isidrop** [Grapheel/IRIS#2]
## Tell us about your system and the issue with IRIS

1. I'm using IRIS as a volunteer.
2. I am using assistive technology: No
3. My device is a: Dell desktop
4. My operating system is: Windows 10
5. The web browser I'm using is: Chrome (64 bits)
6. The version of the web browser is: Version 64.0.3282.167

### Bugs found with description

I found the following bug(s):

- [ ] Help computer scientist student
 * Can't choose "Computer science students" in the "I feel like helping" combo box.

**Comment by tingard** [comment]
Hi @Isidrop, thanks for the bug report.
Do you mean you can't see the option from the dropdown, or that clicking the option does nothing?

**Comment by Isidrop** [comment]
I can't see it, see below:
https://ibb.co/fkWh7c

**Comment by tingard** [comment]
Ah okay, on my screen the computer science option is hidden and I need to scroll to see it, does that work? If so I'll add a permanent scroll bar to make things more obvious.

**Comment by damienablart** [comment]
Of geez haha
I can indeed scroll, but the combo box is really large on my screen and it makes it totally not obvious!
I close it then! Thanks!

**Comment by tingard** [comment]
Thanks for raising this though: as we add more subjects it's gonna need to be super obvious that people ought to scroll to see all the options.
